config/routes.rb
Rails.application.routes.draw do
  root 'students#index'

  resources :students, only: [:index, :show]
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all
	end

	def show
		@student = Student.find_by_id(params[:id])
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NycdaSma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>Students</h1>

<ul>
	<% @students.each do |student| %>
	  <li>
	  	<span><%= link_to(student.email, student_path(student)) %></span>
	  	<span><%= student.first_name %></span> |
	  	<span><%= student.last_name %></span> |
	  </li>	
	<% end %> 
</ul>	 	

app/views/students/show.html.erb
<h1>Student Profile</h1>

<p><%= link_to "Back to Students", students_path %></p>


<% if @student %>
	<p><span>Email: </span><%= @student.email %></p>
	<p><span>First Name: </span><%= @student.first_name %></p>
	<p><span>Last Name: </span><%= @student.last_name %></p>
	<p><span>Phone: </span><%= @student.phone %></p>
	<p><span>Status: </span><%= @student.status %></p>
<% else %>
	<p> Student not found </p>
<% end %>	